package com.shop.freight.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.shop.common.exception.*; import com.shop.freight.dto.*; import com.shop.freight.entity.*; import com.shop.freight.mapper.*; import com.shop.freight.service.FreightTemplateService; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.util.*; import java.util.stream.*;
@Service @RequiredArgsConstructor public class FreightTemplateServiceImpl implements FreightTemplateService {
 private final FreightTemplateMapper templateMapper; private final FreightTemplateRuleMapper ruleMapper;
 public List<FreightTemplateVO> list(Long merchantId){ return templateMapper.selectList(new LambdaQueryWrapper<FreightTemplate>().eq(FreightTemplate::getMerchantId,merchantId).orderByDesc(FreightTemplate::getUpdatedAt)).stream().map(this::vo).toList(); }
 public FreightTemplateVO get(Long merchantId,Long id){ return vo(owned(merchantId,id)); }
 @Transactional public Long create(Long merchantId,FreightTemplateRequest r){ validate(r); FreightTemplate t=new FreightTemplate();t.setMerchantId(merchantId);t.setName(r.getName().trim());t.setEnabled(flag(r.getEnabled()));t.setVersion(1L);templateMapper.insert(t); saveRules(t.getId(),r);return t.getId(); }
 @Transactional public void update(Long merchantId,Long id,FreightTemplateRequest r){validate(r);FreightTemplate t=owned(merchantId,id);t.setName(r.getName().trim());t.setEnabled(flag(r.getEnabled()));t.setVersion(t.getVersion()+1);templateMapper.updateById(t);ruleMapper.delete(new LambdaQueryWrapper<FreightTemplateRule>().eq(FreightTemplateRule::getTemplateId,id));saveRules(id,r);}
 @Transactional public void delete(Long merchantId,Long id){owned(merchantId,id);ruleMapper.delete(new LambdaQueryWrapper<FreightTemplateRule>().eq(FreightTemplateRule::getTemplateId,id));templateMapper.deleteById(id);}
 public FreightQuote quote(Long merchantId,String region,List<Line> lines,BigDecimal activityDiscount){
  if(region==null||region.isBlank()) throw new BusinessException(ErrorCode.ADDRESS_NOT_FOUND.getCode(),"收货地址地区不能为空");
  Map<Long,List<Line>> groups=lines.stream().collect(Collectors.groupingBy(l->l.product().getFreightTemplateId())); FreightQuote result=new FreightQuote();
  if(groups.containsKey(null)) throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"商品未配置运费模板");
  BigDecimal total=lines.stream().map(Line::amount).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal allocated=BigDecimal.ZERO; List<Map.Entry<Long,List<Line>>> entries=new ArrayList<>(groups.entrySet());
  for(int i=0;i<entries.size();i++){var e=entries.get(i); FreightTemplate t=owned(merchantId,e.getKey()); if(!Integer.valueOf(1).equals(t.getEnabled())) throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"商品运费模板未启用"); int weight=e.getValue().stream().mapToInt(l->{if(l.sku().getWeightGram()==null||l.sku().getWeightGram()<1)throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"商品规格未配置重量");return l.sku().getWeightGram()*l.quantity();}).sum(); BigDecimal amount=e.getValue().stream().map(Line::amount).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal discount=i==entries.size()-1?activityDiscount.subtract(allocated):activityDiscount.multiply(amount).divide(total,2,RoundingMode.HALF_UP); allocated=allocated.add(discount); FreightTemplateRule rule=match(t.getId(),region); BigDecimal merchandise=amount.subtract(discount).max(BigDecimal.ZERO); boolean free=rule.getFreeThresholdAmount()!=null&&merchandise.compareTo(rule.getFreeThresholdAmount())>=0; BigDecimal fee=free?BigDecimal.ZERO:fee(weight,rule); FreightQuote.Item item=new FreightQuote.Item();item.setTemplateId(t.getId());item.setVersion(t.getVersion());item.setWeightGram(weight);item.setMerchandiseAmount(amount);item.setActivityDiscountAmount(discount);item.setFreightAmount(fee);item.setFreeShipping(free);item.setMatchedRegion(region);result.getItems().add(item);result.setAmount(result.getAmount().add(fee)); }
  return result;
 }
 private BigDecimal fee(int weight,FreightTemplateRule r){if(weight<=r.getFirstWeightGram())return r.getFirstFee();int n=(int)Math.ceil((weight-r.getFirstWeightGram())/(double)r.getAdditionalWeightGram());return r.getFirstFee().add(r.getAdditionalFee().multiply(BigDecimal.valueOf(n))).setScale(2,RoundingMode.HALF_UP);}
 private FreightTemplateRule match(Long id,String region){String[] p=region.trim().split("[ /,，]");String province=p.length>0?p[0]:"";String city=p.length>1?p[1]:"";List<FreightTemplateRule> rs=ruleMapper.selectList(new LambdaQueryWrapper<FreightTemplateRule>().eq(FreightTemplateRule::getTemplateId,id));return rs.stream().filter(x->province.equals(x.getProvince())&&city.equals(x.getCity())&&!city.isBlank()).findFirst().or(()->rs.stream().filter(x->province.equals(x.getProvince())&&x.getCity().isBlank()).findFirst()).or(()->rs.stream().filter(x->x.getProvince().isBlank()).findFirst()).orElseThrow(()->new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"运费模板缺少默认规则"));}
 private void saveRules(Long id,FreightTemplateRequest r){for(var x:r.getRules()){FreightTemplateRule e=new FreightTemplateRule();e.setTemplateId(id);e.setProvince(blank(x.getProvince()));e.setCity(blank(x.getCity()));e.setFirstWeightGram(x.getFirstWeightGram());e.setFirstFee(x.getFirstFee());e.setAdditionalWeightGram(x.getAdditionalWeightGram());e.setAdditionalFee(x.getAdditionalFee());e.setFreeThresholdAmount(x.getFreeThresholdAmount());ruleMapper.insert(e);}}
 private FreightTemplateVO vo(FreightTemplate t){FreightTemplateVO v=new FreightTemplateVO();v.setId(t.getId());v.setName(t.getName());v.setEnabled(t.getEnabled());v.setVersion(t.getVersion());ruleMapper.selectList(new LambdaQueryWrapper<FreightTemplateRule>().eq(FreightTemplateRule::getTemplateId,t.getId()).orderByAsc(FreightTemplateRule::getId)).forEach(x->{FreightTemplateVO.Rule r=new FreightTemplateVO.Rule();org.springframework.beans.BeanUtils.copyProperties(x,r);v.getRules().add(r);});return v;}
 private FreightTemplate owned(Long m,Long id){FreightTemplate t=templateMapper.selectById(id);if(t==null||!Objects.equals(m,t.getMerchantId()))throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"运费模板不存在");return t;}
 private void validate(FreightTemplateRequest r){if(r.getEnabled()==null||(r.getEnabled()!=0&&r.getEnabled()!=1))throw new BusinessException(ErrorCode.PARAM_ERROR);long defaults=r.getRules().stream().filter(x->blank(x.getProvince()).isBlank()).count();if(defaults!=1)throw new BusinessException(ErrorCode.PARAM_ERROR.getCode(),"运费模板必须且只能有一条默认规则");Set<String>s=new HashSet<>();for(var x:r.getRules()){String k=blank(x.getProvince())+"/"+blank(x.getCity());if(!s.add(k)||(!blank(x.getCity()).isBlank()&&blank(x.getProvince()).isBlank()))throw new BusinessException(ErrorCode.PARAM_ERROR.getCode(),"地区规则重复或城市缺少省份");}}
 private int flag(Integer v){return Integer.valueOf(1).equals(v)?1:0;} private String blank(String v){return v==null?"":v.trim();}
}
