<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { businessAnalysisApi, type BusinessAnalysis } from '@/api/businessAnalysis'

const loading = ref(false), range = ref<'7'|'30'|'90'>('30'), report = ref<BusinessAnalysis | null>(null)
const props = withDefaults(defineProps<{ scope?: 'merchant' | 'admin' }>(), { scope: 'merchant' })
const money = (value?: number) => `¥${Number(value || 0).toFixed(2)}`
const percent = (value?: number) => `${(Number(value || 0) * 100).toFixed(1)}%`
const format = (value?: string) => value ? value.replace('T', ' ').slice(0, 16) : '-'
const rangeLabel = computed(() => `最近 ${range.value} 天`)
function localDateTime(value: Date) { const pad = (part: number) => String(part).padStart(2, '0'); return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}T${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}` }
async function load() { loading.value = true; try { const now = new Date(); const params = { from: localDateTime(new Date(now.getTime() - Number(range.value) * 86400000)), to: localDateTime(now) }; report.value = props.scope === 'admin' ? await businessAnalysisApi.adminReport(params) : await businessAnalysisApi.report(params) } finally { loading.value = false } }
function exportRows() { if (!report.value) return; const rows = [['来源','支付订单','支付金额','退款金额','净成交额','实际优惠成本'], ...report.value.sources.map(x => [x.sourceName, x.paidOrderCount, x.paidAmount, x.refundAmount, x.netAmount, x.actualDiscountAmount])]; const blob = new Blob(['\ufeff' + rows.map(x => x.join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `经营归因-${rangeLabel.value}.csv`; a.click(); URL.revokeObjectURL(a.href) }
onMounted(load)
</script>

<template>
  <main class="analysis-page" v-loading="loading">
    <header class="page-header"><div><h1 class="page-title">{{ scope === 'admin' ? '平台经营分析' : '经营分析与归因' }}</h1><p class="page-desc">按支付与退款结果复盘经营表现；仅使用订单、优惠券、邀请和营销执行的直接证据归因。</p></div><div class="actions"><el-select v-model="range" aria-label="统计区间" @change="load"><el-option label="最近 7 天" value="7"/><el-option label="最近 30 天" value="30"/><el-option label="最近 90 天" value="90"/></el-select><el-button @click="exportRows">导出归因</el-button><el-button type="primary" :loading="loading" @click="load">刷新</el-button></div></header>
    <p v-if="report" class="as-of">数据区间 {{ format(report.from) }} 至 {{ format(report.to) }} · 截至 {{ format(report.dataAsOf) }}</p>
    <section class="metric-grid" aria-label="经营核心指标"><article><span>净成交额</span><strong>{{ money(report?.overview.netAmount) }}</strong><small>支付金额减退款成功金额</small></article><article><span>支付金额</span><strong>{{ money(report?.overview.paidAmount) }}</strong><small>{{ report?.overview.paidOrderCount || 0 }} 笔支付订单</small></article><article><span>实际优惠成本</span><strong>{{ money(report?.overview.actualDiscountAmount) }}</strong><small>仅计已产生订单优惠</small></article><article><span>退款率</span><strong>{{ percent(report?.overview.refundRate) }}</strong><small>退款成功金额 / 支付金额</small></article><article><span>客单价</span><strong>{{ money(report?.overview.averageOrderValue) }}</strong><small>{{ report?.overview.paidUserCount || 0 }} 位支付用户</small></article><article><span>归因覆盖率</span><strong>{{ percent(report?.overview.attributionCoverage) }}</strong><small>有直接归因证据的支付订单</small></article></section>
    <section class="panel"><div class="panel-heading"><div><h2>转化漏斗</h2><p>{{ report?.funnel.coverageNote }}</p></div></div><div class="funnel"><div><span>浏览商品</span><strong>{{ report?.funnel.productViewUsers || 0 }}</strong><small>用户</small></div><i>→</i><div><span>加购</span><strong>{{ report?.funnel.addCartUsers || 0 }}</strong><small>{{ percent(report?.funnel.addCartRate) }}</small></div><i>→</i><div><span>提交订单</span><strong>{{ report?.funnel.submitOrderUsers || 0 }}</strong><small>{{ percent(report?.funnel.submitRate) }}</small></div><i>→</i><div><span>支付成功</span><strong>{{ report?.funnel.paidUsers || 0 }}</strong><small>{{ percent(report?.funnel.payRate) }}</small></div></div></section>
    <section class="panel"><div class="panel-heading"><div><h2>来源归因</h2><p>每笔订单仅计入一个主来源；助攻触达不会重复计入成交额。</p></div></div><el-table :data="report?.sources || []" empty-text="当前区间暂无支付订单"><el-table-column prop="sourceName" label="主来源" min-width="160"/><el-table-column prop="paidOrderCount" label="支付订单" width="110"/><el-table-column label="支付金额" min-width="130"><template #default="{ row }">{{ money(row.paidAmount) }}</template></el-table-column><el-table-column label="退款金额" min-width="130"><template #default="{ row }">{{ money(row.refundAmount) }}</template></el-table-column><el-table-column label="净成交额" min-width="130"><template #default="{ row }"><strong>{{ money(row.netAmount) }}</strong></template></el-table-column><el-table-column label="实际优惠成本" min-width="145"><template #default="{ row }">{{ money(row.actualDiscountAmount) }}</template></el-table-column><el-table-column label="订单占比" width="110"><template #default="{ row }">{{ percent(row.coverage) }}</template></el-table-column></el-table></section>
    <section v-if="scope === 'admin'" class="panel"><div class="panel-heading"><div><h2>商户净成交排名</h2><p>按净成交额降序；退款已按退款成功时间扣减。</p></div></div><el-table :data="report?.merchantPerformance || []" empty-text="当前区间暂无支付订单"><el-table-column prop="merchantName" label="商户" min-width="180"/><el-table-column prop="paidOrderCount" label="支付订单" width="110"/><el-table-column label="支付金额" min-width="130"><template #default="{ row }">{{ money(row.paidAmount) }}</template></el-table-column><el-table-column label="退款金额" min-width="130"><template #default="{ row }">{{ money(row.refundAmount) }}</template></el-table-column><el-table-column label="净成交额" min-width="140"><template #default="{ row }"><strong>{{ money(row.netAmount) }}</strong></template></el-table-column></el-table></section>
    <el-alert v-if="report" class="definition" type="info" :closable="false" show-icon :title="report.metricDefinition" />
  </main>
</template>

<style scoped>
.analysis-page{width:min(1440px,calc(100% - 56px));margin:28px auto 40px}.page-header,.actions,.panel-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.page-title{margin:0;color:var(--shop-text);font-size:28px}.page-desc,.as-of,.panel-heading p{margin:8px 0 0;color:var(--shop-text-muted);font-size:13px;line-height:1.6}.actions{align-items:center}.actions .el-select{width:128px}.as-of{margin-bottom:18px}.metric-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}.metric-grid article,.panel{border:1px solid var(--shop-border);border-radius:12px;background:var(--shop-surface,#fff)}.metric-grid article{min-height:122px;padding:18px;box-sizing:border-box}.metric-grid span,.metric-grid strong,.metric-grid small{display:block}.metric-grid span,.metric-grid small{color:var(--shop-text-muted);font-size:12px}.metric-grid strong{margin:14px 0 12px;color:var(--shop-text);font-size:24px;line-height:1;font-variant-numeric:tabular-nums}.panel{margin-top:18px;padding:20px}.panel-heading{margin-bottom:18px}.panel-heading h2{margin:0;color:var(--shop-text);font-size:18px}.funnel{display:flex;align-items:stretch;gap:12px}.funnel>div{flex:1;min-width:0;padding:16px;border-radius:10px;background:var(--shop-bg-soft)}.funnel span,.funnel strong,.funnel small{display:block}.funnel span,.funnel small{color:var(--shop-text-muted);font-size:12px}.funnel strong{margin:10px 0;color:var(--shop-text);font-size:25px;font-variant-numeric:tabular-nums}.funnel i{align-self:center;color:var(--shop-text-muted);font-style:normal}.definition{margin-top:18px}@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:720px){.analysis-page{width:calc(100% - 28px);margin-top:18px}.page-header{flex-direction:column}.actions{width:100%;flex-wrap:wrap}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.funnel{overflow-x:auto}.funnel>div{min-width:150px}}
</style>
