<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { customerOperationsApi, type CustomerSegment, type CustomerTag, type CustomerUser, type SegmentCondition } from '@/api/customerOperations'

const loading = ref(false), segments = ref<CustomerSegment[]>([]), tags = ref<CustomerTag[]>([])
const dialogVisible = ref(false), usersVisible = ref(false), editing = ref<CustomerSegment | null>(null), viewing = ref<CustomerSegment | null>(null)
const users = ref<CustomerUser[]>([]), userTotal = ref(0), userPage = ref(1)
const form = reactive({ name: '', description: '', segmentType: 'DYNAMIC' as 'DYNAMIC' | 'STATIC', status: 1, logic: 'AND' as 'AND' | 'OR', conditions: [{ field: 'paidOrderCount', operator: 'GTE', value: '1' }] as SegmentCondition[] })
const fieldOptions = [{ value: 'paidOrderCount', label: '已支付订单数' }, { value: 'totalPaidAmount', label: '累计实付金额' }, { value: 'memberLevel', label: '会员等级' }, { value: 'pointsBalance', label: '积分余额' }, { value: 'unusedCouponCount', label: '可用优惠券数' }, { value: 'favoriteCount', label: '收藏商品数' }, { value: 'historyCount', label: '浏览商品数' }, { value: 'tagId', label: '拥有标签' }]
const numericOperators = [{ value: 'GTE', label: '大于等于' }, { value: 'LTE', label: '小于等于' }, { value: 'EQ', label: '等于' }, { value: 'GT', label: '大于' }, { value: 'LT', label: '小于' }]

const tagOptions = computed(() => tags.value.filter((item) => item.status === 1))
async function load() { loading.value = true; try { const [segmentData, tagData] = await Promise.all([customerOperationsApi.segments(), customerOperationsApi.tags()]); segments.value = segmentData; tags.value = tagData } finally { loading.value = false } }
function blankCondition(): SegmentCondition { return { field: 'paidOrderCount', operator: 'GTE', value: '1' } }
function openCreate() { editing.value = null; Object.assign(form, { name: '', description: '', segmentType: 'DYNAMIC', status: 1, logic: 'AND', conditions: [blankCondition()] }); dialogVisible.value = true }
function openEdit(value: unknown) { const item = value as CustomerSegment; editing.value = item; Object.assign(form, { name: item.name, description: item.description || '', segmentType: item.segmentType, status: item.status, logic: item.condition.logic || 'AND', conditions: (item.condition.conditions || []).map((condition) => ({ ...condition })) }); dialogVisible.value = true }
function changeField(condition: SegmentCondition) { condition.operator = condition.field === 'tagId' ? 'HAS' : 'GTE'; condition.value = condition.field === 'tagId' ? String(tagOptions.value[0]?.id || '') : '1' }
function addCondition() { if (form.conditions.length < 8) form.conditions.push(blankCondition()) }
function removeCondition(index: number) { if (form.conditions.length > 1) form.conditions.splice(index, 1) }
async function save() { if (!form.name.trim() || form.conditions.some((condition) => !condition.value)) return ElMessage.warning('请完整填写分群名称和条件'); const payload = { name: form.name.trim(), description: form.description.trim(), segmentType: form.segmentType, status: form.status, condition: { logic: form.logic, conditions: form.conditions } }; if (editing.value) await customerOperationsApi.updateSegment(editing.value.id, payload); else await customerOperationsApi.createSegment(payload); ElMessage.success('分群已保存并计算成员'); dialogVisible.value = false; await load() }
async function rebuild(value: unknown) { const item = value as CustomerSegment; await customerOperationsApi.rebuildSegment(item.id); ElMessage.success('分群已重新计算'); await load() }
async function viewUsers(value: unknown, page = 1) { const item = value as CustomerSegment; viewing.value = item; userPage.value = page; const result = await customerOperationsApi.segmentUsers(item.id, { page, size: 10 }); users.value = result.list || []; userTotal.value = result.total || 0; usersVisible.value = true }
function formatTime(value?: string) { return value ? value.replace('T', ' ').slice(0, 16) : '-' }
onMounted(load)
</script>

<template>
  <div class="segment-page" v-loading="loading"><div class="page-header"><div><h1 class="page-title">用户分群</h1><p class="page-desc">动态分群按最新指标实时计算；静态分群保存当前成员快照。</p></div><el-button type="primary" @click="openCreate">新建分群</el-button></div>
    <el-table :data="segments" empty-text="暂无分群"><el-table-column prop="name" label="分群名称" min-width="180" /><el-table-column prop="description" label="说明" min-width="200" show-overflow-tooltip /><el-table-column label="类型" width="110"><template #default="{ row }"><el-tag effect="plain">{{ row.segmentType === 'STATIC' ? '静态快照' : '动态人群' }}</el-tag></template></el-table-column><el-table-column label="成员数" width="110" align="right"><template #default="{ row }">{{ row.memberCount || 0 }}</template></el-table-column><el-table-column label="更新时间" min-width="160"><template #default="{ row }">{{ formatTime(row.calculatedAt) }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{ row }"><el-tag :type="row.status === 1 ? 'success' : 'info'">{{ row.status === 1 ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="viewUsers(row)">查看用户</el-button><el-button link @click="rebuild(row)">重新计算</el-button><el-button link @click="openEdit(row)">编辑</el-button></template></el-table-column></el-table>
  </div>
  <el-dialog v-model="dialogVisible" :title="editing ? '编辑分群' : '新建分群'" width="720px" destroy-on-close><el-form label-width="90px"><el-form-item label="分群名称"><el-input v-model="form.name" maxlength="64" show-word-limit /></el-form-item><el-form-item label="分群说明"><el-input v-model="form.description" maxlength="255" show-word-limit /></el-form-item><el-form-item label="成员类型"><el-radio-group v-model="form.segmentType"><el-radio value="DYNAMIC">动态人群</el-radio><el-radio value="STATIC">静态快照</el-radio></el-radio-group></el-form-item><el-form-item label="条件关系"><el-radio-group v-model="form.logic"><el-radio value="AND">同时满足</el-radio><el-radio value="OR">满足任一</el-radio></el-radio-group></el-form-item><el-form-item label="筛选条件"><div class="condition-list"><div v-for="(condition, index) in form.conditions" :key="index" class="condition-row"><el-select v-model="condition.field" @change="changeField(condition)"><el-option v-for="item in fieldOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="condition.operator" :disabled="condition.field === 'tagId'"><el-option v-if="condition.field === 'tagId'" label="拥有" value="HAS" /><el-option v-for="item in numericOperators" v-else :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-if="condition.field === 'tagId'" v-model="condition.value"><el-option v-for="tag in tagOptions" :key="tag.id" :label="tag.name" :value="String(tag.id)" /></el-select><el-input v-else v-model="condition.value" inputmode="decimal" /><el-button link type="danger" :disabled="form.conditions.length === 1" @click="removeCondition(index)">删除</el-button></div><el-button link type="primary" :disabled="form.conditions.length >= 8" @click="addCondition">+ 添加条件</el-button></div></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" @click="save">保存并计算</el-button></template></el-dialog>
  <el-dialog v-model="usersVisible" :title="`分群用户 · ${viewing?.name || ''}`" width="860px"><el-table :data="users" empty-text="当前没有符合条件的用户"><el-table-column label="用户" min-width="180"><template #default="{ row }"><div>{{ row.nickname || `用户 #${row.userId}` }}</div><small>{{ row.phone || '-' }}</small></template></el-table-column><el-table-column label="标签" min-width="200"><template #default="{ row }"><el-tag v-for="tag in row.tags" :key="tag.id" size="small" effect="plain">{{ tag.name }}</el-tag></template></el-table-column><el-table-column label="订单数" width="90" align="right"><template #default="{ row }">{{ row.metric?.paidOrderCount || 0 }}</template></el-table-column><el-table-column label="累计实付" width="120" align="right"><template #default="{ row }">¥{{ Number(row.metric?.totalPaidAmount || 0).toFixed(2) }}</template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="userPage" :page-size="10" :total="userTotal" layout="total, prev, pager, next" @current-change="(page) => viewing && viewUsers(viewing, page)" /></div></el-dialog>
</template>

<style scoped>
.segment-page { width: min(1280px, calc(100% - 56px)); margin: 28px auto 36px; }.page-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 22px; }.page-title { margin: 0; color: var(--shop-text); font-size: 28px; }.page-desc { margin: 8px 0 0; color: var(--shop-text-muted); font-size: 14px; }.condition-list { width: 100%; }.condition-row { display: grid; grid-template-columns: 1.2fr 1fr 1fr auto; gap: 10px; margin-bottom: 10px; }.pagination { display: flex; justify-content: flex-end; margin-top: 18px; } small { color: var(--shop-text-muted); }
</style>
