<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { freightApi, type FreightTemplate, type FreightRule } from '@/api/freight'
const rows=ref<FreightTemplate[]>([]);const loading=ref(false);const visible=ref(false);const editing=ref<number>();
const form=reactive({name:'',enabled:1,rules:[{province:'',city:'',firstWeightGram:1000,firstFee:0,additionalWeightGram:1000,additionalFee:0,freeThresholdAmount:0} as FreightRule]})
async function load(){loading.value=true;try{rows.value=await freightApi.list()}finally{loading.value=false}}
function open(row?:FreightTemplate){editing.value=row?.id;form.name=row?.name||'';form.enabled=row?.enabled??1;form.rules=row?.rules?.map(x=>({...x}))||[{province:'',city:'',firstWeightGram:1000,firstFee:0,additionalWeightGram:1000,additionalFee:0,freeThresholdAmount:0}];visible.value=true}
function add(){form.rules.push({province:'',city:'',firstWeightGram:1000,firstFee:0,additionalWeightGram:1000,additionalFee:0})}
async function save(){if(!form.name.trim())return ElMessage.error('请输入模板名称');if(form.rules.filter(x=>!x.province&&!x.city).length!==1)return ElMessage.error('必须保留一条默认地区规则');const data={name:form.name.trim(),enabled:form.enabled,rules:form.rules};if(editing.value)await freightApi.update(editing.value,data);else await freightApi.create(data);ElMessage.success('已保存');visible.value=false;load()}
async function remove(row:FreightTemplate){await ElMessageBox.confirm(`删除「${row.name}」后商品将无法使用该模板，确定继续？`,'删除模板',{type:'warning'});await freightApi.remove(row.id);ElMessage.success('已删除');load()}
onMounted(load)
</script>
<template><div class="page" v-loading="loading"><div class="page-header"><div><h1 class="page-title">运费模板</h1><p class="page-desc">按收货省市和 SKU 重量计算普通订单运费；满额包邮按活动优惠后金额判断。</p></div><el-button type="primary" @click="open()">新建模板</el-button></div><el-table :data="rows" empty-text="暂无运费模板，请先创建一份模板"><el-table-column prop="name" label="模板名称" min-width="180"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="地区规则" min-width="380"><template #default="{row}"><div v-for="rule in row.rules" :key="rule.province+rule.city">{{rule.province||'默认地区'}}{{rule.city?' / '+rule.city:''}}：首{{rule.firstWeightGram}}g ¥{{rule.firstFee}}，续{{rule.additionalWeightGram}}g ¥{{rule.additionalFee}}，{{rule.freeThresholdAmount != null?'满 ¥'+rule.freeThresholdAmount+' 包邮':'不包邮'}}</div></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="open(row as FreightTemplate)">编辑</el-button><el-button link type="danger" @click="remove(row as FreightTemplate)">删除</el-button></template></el-table-column></el-table><el-dialog v-model="visible" :title="editing?'编辑运费模板':'新建运费模板'" width="780px"><el-form label-width="100px"><el-form-item label="模板名称"><el-input v-model="form.name" maxlength="64"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.enabled"><el-radio :value="1">启用</el-radio><el-radio :value="0">停用</el-radio></el-radio-group></el-form-item><el-divider>地区规则</el-divider><div v-for="(rule,index) in form.rules" :key="index" class="rule"><el-input v-model="rule.province" placeholder="省（留空为默认）"/><el-input v-model="rule.city" placeholder="市（可留空）"/><el-input-number v-model="rule.firstWeightGram" :min="1"/> <span>克 ¥</span><el-input-number v-model="rule.firstFee" :min="0" :precision="2"/><el-input-number v-model="rule.additionalWeightGram" :min="1"/><span>克 ¥</span><el-input-number v-model="rule.additionalFee" :min="0" :precision="2"/><el-input-number v-model="rule.freeThresholdAmount" :min="0" :precision="2" placeholder="包邮门槛"/><el-button link type="danger" :disabled="form.rules.length===1" @click="form.rules.splice(index,1)">删除</el-button></div><el-button plain @click="add">添加地区规则</el-button></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.rule{display:grid;grid-template-columns:110px 110px 90px 24px 90px 90px 24px 90px 110px 48px;gap:8px;align-items:center;margin:10px 0}.page{max-width:1280px}.rule :deep(.el-input-number){width:100%}</style>
