<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { merchantCategoryApi, type MerchantCategoryVO } from '@/api/category'
import { couponTemplateApi, pointsApi, type CouponTemplate, type MemberDayActivity, type PointsProduct, type PointsRule } from '@/api/marketing'
import { productApi, type ProductDetailVO, type ProductListVO } from '@/api/product'
const saving=ref(false), products=ref<any[]>([]), goods=ref<ProductListVO[]>([]), coupons=ref<CouponTemplate[]>([]), categories=ref<MerchantCategoryVO[]>([]), scopeIds=ref<number[]>([])
const rule=ref<PointsRule>({registerPoints:0,payAmountYuan:1,pointsPerYuan:1,signInPoints:5,validDays:0,deductionPerYuan:100,deductionMaxPoints:0,status:0})
const day=ref<MemberDayActivity>({name:'积分会员日',dayOfMonth:18,startTime:'00:00:00',endTime:'23:59:59',doublePoints:1,couponTemplateId:null,productScopeType:0,productScopeIdsJson:'',stackable:0,status:0})
const categoryOptions=computed(()=>{const out:MerchantCategoryVO[]=[];const walk=(xs:MerchantCategoryVO[])=>xs.forEach(x=>{out.push(x);if(x.children)walk(x.children)});walk(categories.value);return out})
function emptyProduct(){return {title:'',image:'',pointsPrice:100,stock:0,perUserLimit:1,status:0,productId:null,skuId:null,couponTemplateId:null,skuOptions:[]}}
function couponLabel(c:CouponTemplate){return `${c.name} · ¥${c.amount}${Number(c.thresholdAmount)>0?`（满${c.thresholdAmount}可用）`:''}`}
async function loadSku(row:any,reset=false){if(!row.productId){row.skuId=null;row.skuOptions=[];return};const d:ProductDetailVO=await productApi.get(row.productId);row.skuOptions=d.skus||[];if(reset){row.skuId=null;const p=goods.value.find(x=>x.id===row.productId);if(!row.title&&p)row.title=p.name}}
async function onProductChange(row:any){if(row.productId)row.couponTemplateId=null;await loadSku(row,true)}
function onCouponChange(row:any){if(!row.couponTemplateId)return;row.productId=null;row.skuId=null;row.skuOptions=[]}
async function load(){const [r,p,d,g,c,t]=await Promise.all([pointsApi.rule(),pointsApi.products(),pointsApi.memberDay(),productApi.page({page:1,size:200,status:1,auditStatus:1}),couponTemplateApi.list(),merchantCategoryApi.enabledTree()]);rule.value={...rule.value,...(r||{})};products.value=p||[];goods.value=g?.list||[];coupons.value=c||[];categories.value=t||[];if(d){day.value=d;try{scopeIds.value=JSON.parse(d.productScopeIdsJson||'[]')}catch{scopeIds.value=[]}};await Promise.all(products.value.filter(x=>x.productId).map(x=>loadSku(x)))}
async function saveRule(){saving.value=true;try{await pointsApi.saveRule(rule.value);ElMessage.success('积分规则已保存')}finally{saving.value=false}}
async function saveDay(){saving.value=true;try{day.value.productScopeIdsJson=day.value.productScopeType===0?'':JSON.stringify(scopeIds.value);const {id,active,statusText,...payload}=day.value;await pointsApi.saveMemberDay(payload);ElMessage.success('会员日配置已保存')}finally{saving.value=false}}
async function saveProduct(row:any){if(!row.title||!row.pointsPrice)return ElMessage.warning('请完整填写兑换名称和所需积分');if(!row.couponTemplateId&&(!row.productId||!row.skuId))return ElMessage.warning('请选择优惠券模板，或同时选择商品和 SKU');const {id,skuOptions,physical,redeemedCount,...payload}=row;if(id)await pointsApi.updateProduct(id,payload as PointsProduct);else row.id=await pointsApi.createProduct(payload as PointsProduct);ElMessage.success('兑换项已保存')}
onMounted(load)
</script>
<template><div class="points-page page"><div class="page-header"><div><span class="page-kicker">MEMBER POINTS</span><h1 class="page-title">积分会员日</h1><p class="page-desc">配置积分发放、纯积分包邮兑换和每月固定会员日。</p></div><el-button @click="load">刷新</el-button></div><el-alert title="专享券模板：会员日在活动时段内可领取的已配置优惠券。" type="info" show-icon :closable="false" class="tip"/>
<el-card shadow="never" class="block"><template #header>积分规则</template><el-form :model="rule" label-width="150px" class="inline-form"><el-form-item label="注册赠分"><el-input-number v-model="rule.registerPoints" :min="0"/></el-form-item><el-form-item label="支付赠分"><span>每实付</span><el-input-number v-model="rule.payAmountYuan" :min="1"/><span>元，赠送</span><el-input-number v-model="rule.pointsPerYuan" :min="0"/><span>积分</span></el-form-item><el-form-item label="每日签到积分"><el-input-number v-model="rule.signInPoints" :min="0"/></el-form-item><el-form-item label="积分有效期（天）"><el-input-number v-model="rule.validDays" :min="0"/><span class="hint">0 为永久有效</span></el-form-item><el-form-item label="规则状态"><el-switch v-model="rule.status" :active-value="1" :inactive-value="0"/></el-form-item><el-form-item><el-button type="primary" :loading="saving" @click="saveRule">保存规则</el-button></el-form-item></el-form></el-card>
<el-card shadow="never" class="block"><template #header>会员日活动</template><el-form :model="day" label-width="150px" class="inline-form"><el-form-item label="活动名称"><el-input v-model="day.name"/></el-form-item><el-form-item label="每月日期"><el-input-number v-model="day.dayOfMonth" :min="1" :max="31"/></el-form-item><el-form-item label="活动时段"><el-time-picker v-model="day.startTime" value-format="HH:mm:ss" format="HH:mm"/><span class="to">至</span><el-time-picker v-model="day.endTime" value-format="HH:mm:ss" format="HH:mm"/></el-form-item><el-form-item label="双倍积分"><el-switch v-model="day.doublePoints" :active-value="1" :inactive-value="0"/></el-form-item><el-form-item label="专享券模板"><el-select v-model="day.couponTemplateId" filterable clearable placeholder="搜索券名称"><el-option v-for="c in coupons" :key="c.id" :value="c.id" :label="couponLabel(c)"/></el-select></el-form-item><el-form-item label="适用范围"><el-select v-model="day.productScopeType"><el-option :value="0" label="全部商品"/><el-option :value="1" label="指定商品"/><el-option :value="2" label="指定分类"/></el-select></el-form-item><el-form-item v-if="day.productScopeType===1" label="选择商品"><el-select v-model="scopeIds" multiple filterable placeholder="输入商品名称搜索"><el-option v-for="p in goods" :key="p.id" :value="p.id" :label="`${p.name} · ID ${p.id}`"/></el-select></el-form-item><el-form-item v-if="day.productScopeType===2" label="选择分类"><el-select v-model="scopeIds" multiple filterable placeholder="输入分类名称搜索"><el-option v-for="c in categoryOptions" :key="c.id" :value="c.id" :label="c.name"/></el-select></el-form-item><el-form-item label="允许与券/满减叠加"><el-switch v-model="day.stackable" :active-value="1" :inactive-value="0"/></el-form-item><el-form-item label="活动状态"><el-switch v-model="day.status" :active-value="1" :inactive-value="0"/></el-form-item><el-form-item><el-button type="primary" :loading="saving" @click="saveDay">保存会员日</el-button></el-form-item></el-form></el-card>
<el-card shadow="never" class="block"><template #header><div class="card-title"><span>积分兑换项</span><el-button type="primary" @click="products.push(emptyProduct())">新增兑换项</el-button></div></template><el-table :data="products"><el-table-column label="名称" min-width="180"><template #default="{row}"><el-input v-model="row.title"/></template></el-table-column><el-table-column label="商品" width="220"><template #default="{row}"><el-select v-model="row.productId" filterable clearable :disabled="!!row.couponTemplateId" placeholder="搜索商品" @change="onProductChange(row)"><el-option v-for="p in goods" :key="p.id" :value="p.id" :label="`${p.name} · ID ${p.id}`"/></el-select></template></el-table-column><el-table-column label="SKU" width="200"><template #default="{row}"><el-select v-model="row.skuId" filterable clearable :disabled="!!row.couponTemplateId||!row.productId" placeholder="选择 SKU"><el-option v-for="s in row.skuOptions||[]" :key="s.id" :value="s.id" :label="`${s.specText||'默认规格'} · ID ${s.id}`"/></el-select></template></el-table-column><el-table-column label="券模板" width="220"><template #default="{row}"><el-select v-model="row.couponTemplateId" filterable clearable :disabled="!!row.productId||!!row.skuId" placeholder="搜索优惠券" @change="onCouponChange(row)"><el-option v-for="c in coupons" :key="c.id" :value="c.id" :label="couponLabel(c)"/></el-select></template></el-table-column><el-table-column label="积分 / 库存" width="250" class-name="number-pair"><template #default="{row}"><el-input-number v-model="row.pointsPrice" :min="1"/><el-input-number v-model="row.stock" :min="0"/></template></el-table-column><el-table-column label="每人限兑" width="140"><template #default="{row}"><el-input-number v-model="row.perUserLimit" :min="0"/></template></el-table-column><el-table-column label="上架" width="80"><template #default="{row}"><el-switch v-model="row.status" :active-value="1" :inactive-value="0"/></template></el-table-column><el-table-column label="操作" width="80"><template #default="{row}"><el-button link type="primary" @click="saveProduct(row)">保存</el-button></template></el-table-column></el-table></el-card></div></template>
<style scoped>.tip,.block{margin-bottom:18px}.inline-form{max-width:860px}.inline-form :deep(.el-input-number){width:150px;margin:0 10px}.inline-form :deep(.el-select),.inline-form :deep(.el-input){width:420px}.hint{margin-left:10px;color:var(--shop-muted);font-size:12px}.to{margin:0 10px}.card-title{display:flex;justify-content:space-between;align-items:center}.el-table :deep(.el-select){width:100%}.el-table :deep(.el-input-number){width:130px}.el-table :deep(.number-pair .el-input-number){width:116px;margin-right:8px}</style>
