package com.shop.engagement.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.shop.common.exception.*; import com.shop.common.response.PageResult; import com.shop.engagement.dto.*; import com.shop.engagement.entity.*; import com.shop.engagement.mapper.*; import com.shop.engagement.service.ProductEngagementService; import com.shop.order.entity.OrderItem; import com.shop.order.mapper.OrderItemMapper; import com.shop.product.entity.Product; import com.shop.product.mapper.ProductMapper; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class ProductEngagementServiceImpl implements ProductEngagementService {
 private final ProductReviewMapper reviewMapper; private final ProductQuestionMapper questionMapper; private final UserProductFavoriteMapper favoriteMapper; private final UserProductHistoryMapper historyMapper; private final ProductMapper productMapper; private final OrderItemMapper orderItemMapper; private final ObjectMapper objectMapper;
 public EngagementVO detail(Long userId,Long merchantId,Long productId){EngagementVO v=new EngagementVO();List<ProductReview> all=reviewMapper.selectList(new LambdaQueryWrapper<ProductReview>().eq(ProductReview::getMerchantId,merchantId).eq(ProductReview::getProductId,productId).eq(ProductReview::getStatus,1).orderByDesc(ProductReview::getCreatedAt));v.setReviewCount(all.size());v.setAverageRating(all.isEmpty()?0:all.stream().mapToInt(ProductReview::getRating).average().orElse(0));all.stream().limit(20).map(this::reviewVo).forEach(v.getReviews()::add);List<ProductQuestion> qs=questionMapper.selectList(new LambdaQueryWrapper<ProductQuestion>().eq(ProductQuestion::getMerchantId,merchantId).eq(ProductQuestion::getProductId,productId).eq(ProductQuestion::getStatus,1).orderByDesc(ProductQuestion::getCreatedAt));v.setQuestionCount(qs.size());qs.stream().limit(20).map(this::questionVo).forEach(v.getQuestions()::add);if(userId!=null)v.setFavorite(favoriteMapper.selectCount(new LambdaQueryWrapper<UserProductFavorite>().eq(UserProductFavorite::getUserId,userId).eq(UserProductFavorite::getMerchantId,merchantId).eq(UserProductFavorite::getProductId,productId))>0);return v;}
 @Transactional public void recordHistory(Long uid,Long mid,Long pid){mustProduct(mid,pid);UserProductHistory h=historyMapper.selectOne(new LambdaQueryWrapper<UserProductHistory>().eq(UserProductHistory::getUserId,uid).eq(UserProductHistory::getMerchantId,mid).eq(UserProductHistory::getProductId,pid));if(h==null){h=new UserProductHistory();h.setUserId(uid);h.setMerchantId(mid);h.setProductId(pid);h.setViewCount(1);h.setLastViewedAt(LocalDateTime.now());historyMapper.insert(h);}else{h.setViewCount(h.getViewCount()+1);h.setLastViewedAt(LocalDateTime.now());historyMapper.updateById(h);}}
 @Transactional public void favorite(Long uid,Long mid,Long pid,boolean value){if(value)mustProduct(mid,pid);UserProductFavorite f=favoriteMapper.selectOne(new LambdaQueryWrapper<UserProductFavorite>().eq(UserProductFavorite::getUserId,uid).eq(UserProductFavorite::getMerchantId,mid).eq(UserProductFavorite::getProductId,pid));if(value&&f==null){f=new UserProductFavorite();f.setUserId(uid);f.setMerchantId(mid);f.setProductId(pid);favoriteMapper.insert(f);}if(!value&&f!=null)favoriteMapper.deleteById(f.getId());}
 public PageResult<EngagementVO.ProductRecord> favorites(Long uid,Long mid,int p,int s){Page<UserProductFavorite> page=favoriteMapper.selectPage(new Page<>(pageNo(p),pageSize(s)),new LambdaQueryWrapper<UserProductFavorite>().eq(UserProductFavorite::getUserId,uid).eq(UserProductFavorite::getMerchantId,mid).orderByDesc(UserProductFavorite::getCreatedAt));Map<Long,Product> products=products(page.getRecords().stream().map(UserProductFavorite::getProductId).toList());return PageResult.of(page.getRecords().stream().map(x->productRecord(products.get(x.getProductId()),x.getProductId(),x.getCreatedAt(),null,null)).toList(),page.getTotal(),(int)page.getCurrent(),(int)page.getSize());}
 public PageResult<EngagementVO.ProductRecord> histories(Long uid,Long mid,int p,int s){Page<UserProductHistory> page=historyMapper.selectPage(new Page<>(pageNo(p),pageSize(s)),new LambdaQueryWrapper<UserProductHistory>().eq(UserProductHistory::getUserId,uid).eq(UserProductHistory::getMerchantId,mid).orderByDesc(UserProductHistory::getLastViewedAt));Map<Long,Product> products=products(page.getRecords().stream().map(UserProductHistory::getProductId).toList());return PageResult.of(page.getRecords().stream().map(x->productRecord(products.get(x.getProductId()),x.getProductId(),null,x.getLastViewedAt(),x.getViewCount())).toList(),page.getTotal(),(int)page.getCurrent(),(int)page.getSize());}
 @Transactional public void removeHistory(Long uid,Long mid,Long pid){historyMapper.delete(new LambdaQueryWrapper<UserProductHistory>().eq(UserProductHistory::getUserId,uid).eq(UserProductHistory::getMerchantId,mid).eq(UserProductHistory::getProductId,pid));}
 @Transactional public void clearHistory(Long uid,Long mid){historyMapper.delete(new LambdaQueryWrapper<UserProductHistory>().eq(UserProductHistory::getUserId,uid).eq(UserProductHistory::getMerchantId,mid));}
 @Transactional public Long review(Long uid,Long mid,EngagementRequests.Review r){OrderItem item=orderItemMapper.selectReviewable(r.getOrderItemId(),uid,mid);if(item==null)throw new BusinessException(ErrorCode.ORDER_STATUS_NOT_ALLOWED.getCode(),"仅可评价已完成的本人订单商品");if(reviewMapper.selectCount(new LambdaQueryWrapper<ProductReview>().eq(ProductReview::getOrderItemId,item.getId()))>0)throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"该商品已评价");ProductReview x=new ProductReview();x.setMerchantId(mid);x.setProductId(item.getProductId());x.setOrderItemId(item.getId());x.setOrderNo(item.getOrderNo());x.setUserId(uid);x.setRating(r.getRating());x.setContent(trim(r.getContent()));x.setImagesJson(json(r.getImages()));x.setAnonymous(flag(r.getAnonymous()));x.setStatus(1);x.setHiddenReason("");x.setMerchantReply("");reviewMapper.insert(x);return x.getId();}
 @Transactional public Long question(Long uid,Long mid,EngagementRequests.Question r){mustProduct(mid,r.getProductId());ProductQuestion x=new ProductQuestion();x.setMerchantId(mid);x.setProductId(r.getProductId());x.setUserId(uid);x.setContent(r.getContent().trim());x.setAnonymous(flag(r.getAnonymous()));x.setPurchased(orderItemMapper.countPaidProduct(r.getProductId(),uid,mid)>0?1:0);x.setStatus(1);x.setHiddenReason("");x.setAnswer("");questionMapper.insert(x);return x.getId();}
 public PageResult<EngagementVO.Review> myReviews(Long uid,Long mid,int p,int s){Page<ProductReview> page=reviewMapper.selectPage(new Page<>(p,s),new LambdaQueryWrapper<ProductReview>().eq(ProductReview::getUserId,uid).eq(ProductReview::getMerchantId,mid).orderByDesc(ProductReview::getCreatedAt));return PageResult.of(page.getRecords().stream().map(this::reviewVo).toList(),page.getTotal(),p,s);}
 public PageResult<EngagementVO.Question> questions(Long mid,int p,int s){Page<ProductQuestion> page=questionMapper.selectPage(new Page<>(p,s),new LambdaQueryWrapper<ProductQuestion>().eq(ProductQuestion::getMerchantId,mid).orderByDesc(ProductQuestion::getCreatedAt));return PageResult.of(page.getRecords().stream().map(this::questionVo).toList(),page.getTotal(),p,s);}
 @Transactional public void answer(Long mid,Long user,Long id,EngagementRequests.Answer r){ProductQuestion q=ownedQuestion(mid,id);q.setAnswer(r.getAnswer().trim());q.setAnsweredBy(user);q.setAnsweredAt(LocalDateTime.now());questionMapper.updateById(q);}
 @Transactional public void hideReview(Long mid,Long id,EngagementRequests.Hide r){ProductReview x=ownedReview(mid,id);x.setStatus(0);x.setHiddenReason(trim(r.getReason()));reviewMapper.updateById(x);}
 @Transactional public void hideQuestion(Long mid,Long id,EngagementRequests.Hide r){ProductQuestion x=ownedQuestion(mid,id);x.setStatus(0);x.setHiddenReason(trim(r.getReason()));questionMapper.updateById(x);}
 private EngagementVO.Review reviewVo(ProductReview x){EngagementVO.Review v=new EngagementVO.Review();v.setId(x.getId());v.setRating(x.getRating());v.setContent(x.getContent());v.setImages(images(x.getImagesJson()));v.setUserName(Integer.valueOf(1).equals(x.getAnonymous())?"匿名用户":"已购用户");v.setMerchantReply(x.getMerchantReply());v.setCreatedAt(x.getCreatedAt());return v;}
 private Map<Long,Product> products(List<Long> ids){if(ids.isEmpty())return Map.of();return productMapper.selectBatchIds(ids).stream().collect(java.util.stream.Collectors.toMap(Product::getId,x->x));} private EngagementVO.ProductRecord productRecord(Product p,Long productId,LocalDateTime createdAt,LocalDateTime lastViewedAt,Integer viewCount){EngagementVO.ProductRecord v=new EngagementVO.ProductRecord();v.setProductId(productId);v.setCreatedAt(createdAt);v.setLastViewedAt(lastViewedAt);v.setViewCount(viewCount);if(p==null){v.setName("商品已下架");v.setAvailable(false);return v;}v.setName(p.getName());v.setMainImage(p.getMainImage());v.setMinPrice(p.getMinPrice());v.setAvailable(Integer.valueOf(1).equals(p.getStatus())&&Integer.valueOf(1).equals(p.getAuditStatus()));return v;}
 private EngagementVO.Question questionVo(ProductQuestion x){EngagementVO.Question v=new EngagementVO.Question();v.setId(x.getId());v.setContent(x.getContent());v.setPurchased(Integer.valueOf(1).equals(x.getPurchased()));v.setUserName(Integer.valueOf(1).equals(x.getAnonymous())?"匿名用户":"用户");v.setAnswer(x.getAnswer());v.setCreatedAt(x.getCreatedAt());return v;}
 private ProductQuestion ownedQuestion(Long m,Long id){ProductQuestion q=questionMapper.selectById(id);if(q==null||!Objects.equals(m,q.getMerchantId()))throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"商品问答不存在");return q;} private ProductReview ownedReview(Long m,Long id){ProductReview q=reviewMapper.selectById(id);if(q==null||!Objects.equals(m,q.getMerchantId()))throw new BusinessException(ErrorCode.BIZ_ERROR.getCode(),"商品评价不存在");return q;} private void mustProduct(Long m,Long id){Product p=productMapper.selectById(id);if(p==null||!Objects.equals(m,p.getMerchantId()))throw new BusinessException(ErrorCode.PRODUCT_NOT_FOUND);} private int pageNo(int p){return Math.max(1,p);} private int pageSize(int s){return Math.min(50,Math.max(1,s));} private int flag(Integer x){return Integer.valueOf(1).equals(x)?1:0;} private String trim(String s){return s==null?"":s.trim();} private String json(List<String> x){try{return objectMapper.writeValueAsString(x==null?List.of():x);}catch(Exception e){throw new BusinessException(ErrorCode.PARAM_ERROR);}} private List<String> images(String v){try{return v==null?List.of():objectMapper.readValue(v,new TypeReference<List<String>>(){});}catch(Exception e){return List.of();}}
}
