# 后台管理页面 - IP:8080 直连
server {
    listen 80 default_server;
    server_name _;

    client_max_body_size 20m;

    root /usr/share/nginx/html/console;
    index index.html;

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /uploads/ {
        alias /usr/share/nginx/html/uploads/;
        expires 30d;
        access_log off;
    }
}
