package com.shop.engagement.controller;
import com.shop.common.response.*; import com.shop.common.security.CurrentUserHolder; import com.shop.engagement.dto.*; import com.shop.engagement.service.ProductEngagementService; import com.shop.wx.config.WxMerchantResolver; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/wx/product-engagement") @RequiredArgsConstructor public class WxProductEngagementController {private final ProductEngagementService service;private final WxMerchantResolver merchant;private Long u(){return CurrentUserHolder.get().getUserId();}private Long m(HttpServletRequest r){return merchant.requireActiveMerchant(r);}
 @GetMapping("/{productId}") public ApiResult<EngagementVO> detail(@PathVariable Long productId,HttpServletRequest r){return ApiResult.success(service.detail(u(),m(r),productId));}
 @PostMapping("/{productId}/history") public ApiResult<Void> history(@PathVariable Long productId,HttpServletRequest r){service.recordHistory(u(),m(r),productId);return ApiResult.success();}
 @PostMapping("/{productId}/favorite") public ApiResult<Void> favorite(@PathVariable Long productId,HttpServletRequest r){service.favorite(u(),m(r),productId,true);return ApiResult.success();}
 @DeleteMapping("/{productId}/favorite") public ApiResult<Void> unfavorite(@PathVariable Long productId,HttpServletRequest r){service.favorite(u(),m(r),productId,false);return ApiResult.success();}
 @GetMapping("/favorites") public ApiResult<PageResult<EngagementVO.ProductRecord>> favorites(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int size,HttpServletRequest r){return ApiResult.success(service.favorites(u(),m(r),page,size));}
 @GetMapping("/history") public ApiResult<PageResult<EngagementVO.ProductRecord>> histories(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int size,HttpServletRequest r){return ApiResult.success(service.histories(u(),m(r),page,size));}
 @DeleteMapping("/history/{productId}") public ApiResult<Void> removeHistory(@PathVariable Long productId,HttpServletRequest r){service.removeHistory(u(),m(r),productId);return ApiResult.success();}
 @DeleteMapping("/history") public ApiResult<Void> clearHistory(HttpServletRequest r){service.clearHistory(u(),m(r));return ApiResult.success();}
 @PostMapping("/reviews") public ApiResult<Long> review(@Valid @RequestBody EngagementRequests.Review q,HttpServletRequest r){return ApiResult.success(service.review(u(),m(r),q));}
 @PostMapping("/questions") public ApiResult<Long> question(@Valid @RequestBody EngagementRequests.Question q,HttpServletRequest r){return ApiResult.success(service.question(u(),m(r),q));}
 @GetMapping("/my-reviews") public ApiResult<PageResult<EngagementVO.Review>> reviews(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int size,HttpServletRequest r){return ApiResult.success(service.myReviews(u(),m(r),page,size));}}
